### ISSUE TITLE
Newsletter-related modules are missing in backend

### ISSUE THREAD

**Issue by lizardat** [terminal42/contao-notification_center#288] opened 2023-06-19 12:51 UTC
Notification Center 1.7.1 in combination with a fresh installation of Contao 4.13.24 / PHP 8.1 doesn't show the newsletter-related modules in the backend.

Only "Passwort vergessen (Notification Center" is available, all others (e.g. "Abonnieren (Notification Center)") are missing.

This does not occur in Notification Center 1.6.14 and Contao 4.13.23 / PHP 7.4.

**Comment by fritzmg** [comment] 2023-06-19 13:05
I am unable to reproduce the problem. All modules are available as expected.

**Comment by fritzmg** [comment] 2023-06-22 09:42
Closing in favor of #289

**Closed by fritzmg** 2023-06-22 09:42 UTC
