### ISSUE TITLE
"Edit Multiple" at gateway queues

### ISSUE THREAD

**Issue by Kahmoon** [terminal42/contao-notification_center#228] opened 2021-02-18 15:24 UTC
Hi,

sometimes (very rare) you have to delete mails which are in the current queue. Maybe there was a mistake in text etc. Actually you have to delete every single entry with 2 clicks (1. delete - 2. are you sure). There is no "edit multiple" like everywhere else in Contao. This would be a really nice enhancement.

<img width="1042" alt="Bildschirmfoto 2021-02-18 um 16 19 56" src="https://user-images.githubusercontent.com/6390770/108378635-78155900-7205-11eb-86ff-4512e6966a44.png">

VG Frank

**Comment by Kahmoon** [comment] 2021-03-16 10:27
Did i open this corretcly? No reply since a month.

**Comment by aschempp** [comment] 2021-09-08 07:57
duplicate of https://github.com/terminal42/contao-notification_center/issues/191

**Closed by aschempp** 2021-09-08 07:57 UTC
