### ISSUE TITLE
Windows - PHP - Attachment by INSERT-TAG - File is not beeing attached to the mail

### ISSUE THREAD

**Issue by isdgroup** [terminal42/contao-notification_center#251] opened 2022-01-07 09:38 UTC
Hi,

maybe i found an Issue reagarding the attachment handling of the notification center by Tokens:

Background:
Windows Server System
Apache Webserver
Contao 4.9
Notification Center 1.6.4

If you create an formular with file attachments and you use the notification center for sending an email with an attachment by tokens the following error is in the PHP Log:

```
[07-Jan-2022 09:59:33 Europe/Berlin] PHP Warning:  move_uploaded_file(C:\Apache24\htdocs\contao49/C:/Apache24/htdocs/contao49/system/tmp/Screenshot 2022-01-04 150903.png): failed to open stream: No such file or directory in C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php on line 315
[07-Jan-2022 09:59:33 Europe/Berlin] PHP Warning:  move_uploaded_file(): Unable to move 'C:\Apache24\htdocs\contao49\system\tmp\php807F.tmp' to 'C:\Apache24\htdocs\contao49/C:/Apache24/htdocs/contao49/system/tmp/Screenshot 2022-01-04 150903.png' in C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php on line 315
[07-Jan-2022 09:59:33 Europe/Berlin] PHP Warning:  chmod(): Invalid argument in C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php on line 286
```

If you use the Contao Formular Manager Form Transmission - Everything is working fine - the File is attached. 

Here the Contao Function for the moving:

Files.php :
```php
(...)
	/**
	 * Move an uploaded file to a folder
	 *
	 * @param string $strSource      The source file
	 * @param string $strDestination The new file path
	 *
	 * @return boolean True if the operation was successful
	 */
	public function move_uploaded_file($strSource, $strDestination)
	{
		$this->validate($strSource, $strDestination);

		return move_uploaded_file($strSource, $this->strRootDir . '/' . $strDestination);
(...)
```

this->strRootDir is already the Contao Root Dir ... but $strDestination has also the full path to the Root Dir. So its double:

In Notification Center ./library/NotificationCenter/Util/Form.php:

```php
class Form
{
    /**
     * Moves an uploaded file to the tmp folder and returns its TL_ROOT relative path.
     * If it was not properly uploaded, the method will return null.
     *
     * @param array $file
     * @return null|string
     */
    public static function getFileUploadPathForToken(array $file)
    {
        // Check if it has been saved by Contao and thus moved to it's final destination already
        if (isset($file['uploaded']) && $file['uploaded'] === true) {
            if (file_exists($file['tmp_name'])) {
                return $file['tmp_name'];
            }

            return null;
        }

        if (!is_uploaded_file($file['tmp_name'])) {

            return null;
        }

        $filePath = sys_get_temp_dir() . '/' . $file['name'];
        \Files::getInstance()->move_uploaded_file($file['tmp_name'], $filePath);
        \Files::getInstance()->chmod($filePath, $GLOBALS['TL_CONFIG']['defaultFileChmod']);

        return $filePath;
    }
}
```

As you can see $filePath uses sys_get_temp_dir()  ... 

I take a look how the core-bundle/src/Resources/contao/form/FormFileUpload does the handling:.
They are working with the rootDir + targetDir:

```php
(...)
rootDir = System::getContainer()->getParameter('kernel.project_dir');

				// Store the file if the upload folder exists
				if ($strUploadFolder != '' && is_dir($rootDir . '/' . $strUploadFolder))
```

Can someone confirm this problem ?

**Comment by fritzmg** [comment] 2022-01-07 11:10
Could you please use the debug mode and post the entire stack trace of the warning?

**Comment by isdgroup** [comment] 2022-01-07 12:13
Hi Fritz,

sure ... here you are:

ErrorException:
Warning: move_uploaded_file(C:\Apache24\htdocs\contao49/C:/Apache24/htdocs/isdgroup.com/contao49/system/tmp/test-v1 (002).pdf): failed to open stream: No such file or directory

 ```
 at C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php:315
  at Contao\Files->move_uploaded_file()
     (C:\Apache24\htdocs\contao49\vendor\terminal42\notification_center\library\NotificationCenter\Util\Form.php:41)
  at NotificationCenter\Util\Form::getFileUploadPathForToken()
     (C:\Apache24\htdocs\contao49\vendor\terminal42\notification_center\classes\tl_form.php:101)
  at NotificationCenter\tl_form->generateTokens()
     (C:\Apache24\htdocs\contao49\vendor\terminal42\notification_center\classes\tl_form.php:60)
  at NotificationCenter\tl_form->sendFormNotification()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\forms\Form.php:561)
  at Contao\Form->processFormData()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\forms\Form.php:259)
  at Contao\Form->compile()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\classes\Hybrid.php:232)
  at Contao\Hybrid->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\forms\Form.php:94)
  at Contao\Form->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:617)
  at Contao\Controller::getContentElement()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:218)
  at Contao\ModuleArticle->compile()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\modules\Module.php:214)
  at Contao\Module->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:71)
  at Contao\ModuleArticle->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:545)
  at Contao\Controller::getArticle()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:386)
  at Contao\Controller::getFrontendModule()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:168)
  at Contao\PageRegular->prepare()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:48)
  at Contao\PageRegular->getResponse()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendIndex.php:337)
  at Contao\FrontendIndex->renderPage()
     (C:\Apache24\htdocs\contao49\vendor\symfony\http-kernel\HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (C:\Apache24\htdocs\contao49\vendor\symfony\http-kernel\HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (C:\Apache24\htdocs\contao49\vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (C:\Apache24\htdocs\contao49\web\preview.php:33) 
```

**Comment by isdgroup** [comment] 2022-01-07 12:14
Hi Fritz,

sure - here you are:

ErrorException:
Warning: move_uploaded_file(C:\Apache24\htdocs\contao49/C:/Apache24/htdocs/contao49/system/tmp/test-v1 (002).pdf): failed to open stream: No such file or directory

  ```
at C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php:315
  at Contao\Files->move_uploaded_file()
     (C:\Apache24\htdocs\contao49\vendor\terminal42\notification_center\library\NotificationCenter\Util\Form.php:41)
  at NotificationCenter\Util\Form::getFileUploadPathForToken()
     (C:\Apache24\htdocs\contao49\vendor\terminal42\notification_center\classes\tl_form.php:101)
  at NotificationCenter\tl_form->generateTokens()
     (C:\Apache24\htdocs\contao49\vendor\terminal42\notification_center\classes\tl_form.php:60)
  at NotificationCenter\tl_form->sendFormNotification()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\forms\Form.php:561)
  at Contao\Form->processFormData()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\forms\Form.php:259)
  at Contao\Form->compile()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\classes\Hybrid.php:232)
  at Contao\Hybrid->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\forms\Form.php:94)
  at Contao\Form->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:617)
  at Contao\Controller::getContentElement()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:218)
  at Contao\ModuleArticle->compile()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\modules\Module.php:214)
  at Contao\Module->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:71)
  at Contao\ModuleArticle->generate()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:545)
  at Contao\Controller::getArticle()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:386)
  at Contao\Controller::getFrontendModule()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:168)
  at Contao\PageRegular->prepare()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:48)
  at Contao\PageRegular->getResponse()
     (C:\Apache24\htdocs\contao49\vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendIndex.php:337)
  at Contao\FrontendIndex->renderPage()
     (C:\Apache24\htdocs\contao49\vendor\symfony\http-kernel\HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (C:\Apache24\htdocs\contao49\vendor\symfony\http-kernel\HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (C:\Apache24\htdocs\contao49\vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (C:\Apache24\htdocs\contao49\web\preview.php:33) 
```

**Comment by fritzmg** [comment] 2022-01-07 12:38
This is a duplicate of #250 

Please install `dev-bugfix/file-handling` and report in that issue whether this fixes your problem.

**Closed by fritzmg** 2022-01-07 12:38 UTC
